FROM golang:1.19-alpine AS builder

RUN apk add build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /server github.com/vkrayzee/testtask-wow/cmd/server

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/db ./db
COPY --from=builder /server .

EXPOSE 8080

ENTRYPOINT [ "./server" ]
