FROM golang:1.19-alpine AS builder

RUN apk add build-base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /client github.com/vkrayzee/testtask-wow/cmd/client

FROM alpine:latest

WORKDIR /app

COPY --from=builder /client .

ENTRYPOINT [ "./client" ]
